poll-service:
  file-to-load: poll-service/src/main/assets/polls.json

spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: default
  application:
    name: poll-service
  data:
    mongodb:
      host: localhost
      port: 27019
      database: polls
      username: doodle
      password: doodle
      auto-index-creation: false