poll-service:
  file-to-load: /assets/polls.json

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: polls
      username: doodle
      password: doodle
      auto-index-creation: false