version: '3.5'

services:

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: polls